# syntax=docker/dockerfile:1.7

FROM gcr.io/distroless/static-debian12:nonroot
ARG TARGETARCH
COPY --chown=65532:65532 .release/docker/data /data
COPY migrations /migrations
COPY --chmod=0755 .release/docker/linux-${TARGETARCH}/migrate /migrate
ENTRYPOINT ["/migrate"]
