import { execFileSync } from "node:child_process";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { afterEach, describe, expect, it } from "vitest";
import { betterAuth } from "better-auth";
import { getMigrations } from "better-auth/db/migration";
import { buildAuthOptions, parseTrustedOrigins, resolveSQLiteDatabasePath } from "./auth";

const repoRoot = path.resolve(__dirname, "../../../..");
const migrationTestTimeoutMs = 60_000;
const originalEnv = { ...process.env };

describe("BetterAuth schema", () => {
  afterEach(() => {
    process.env = { ...originalEnv };
  });

  it("keeps SQLite file URLs aligned with the Go migrator DSN", () => {
    expect(resolveSQLiteDatabasePath("file:./local.db")).toBe("file:./local.db");
    expect(resolveSQLiteDatabasePath("sqlite://./local.db")).toBe("./local.db");
  });

  it("normalizes configured trusted origins", () => {
    expect(parseTrustedOrigins(undefined)).toBeUndefined();
    expect(parseTrustedOrigins(" http://localhost:3001, http://127.0.0.1:3001 ,,")).toEqual([
      "http://localhost:3001",
      "http://127.0.0.1:3001",
    ]);
  });

  it("trusts the incoming request origin for self-hosted OSS access", async () => {
    process.env.BETTER_AUTH_URL = "http://127.0.0.1:3000";
    process.env.PUBLIC_WEB_URL = "http://127.0.0.1:3000";
    process.env.BETTER_AUTH_TRUSTED_ORIGINS = "";

    const database = new Database(":memory:");
    try {
      const options = buildAuthOptions(database);
      expect(typeof options.trustedOrigins).toBe("function");
      if (typeof options.trustedOrigins !== "function") {
        throw new Error("trustedOrigins must be dynamic");
      }

      expect(options.trustedOrigins(new Request("http://109.123.229.21:3000/api/auth/sign-up/email"))).toContain(
        "http://109.123.229.21:3000",
      );
    } finally {
      database.close();
    }
  });

  it("matches the schema generated by BetterAuth after goose migrations run", async () => {
    const databasePath = migrateTempDatabase();

    const database = new Database(databasePath);
    try {
      const migrations = await getMigrations(buildAuthOptions(database));

      expect(migrations.toBeCreated).toEqual([]);
      expect(migrations.toBeAdded).toEqual([]);
    } finally {
      database.close();
    }
  }, migrationTestTimeoutMs);

  it("supports email and password sign-up and sign-in against migrated SQLite", async () => {
    const databasePath = migrateTempDatabase();

    const database = new Database(databasePath);
    try {
      const testAuth = betterAuth(buildAuthOptions(database));
      const email = "owner@example.com";
      const password = "correct-horse-password";

      const signUp = await postAuth(testAuth.handler, "/sign-up/email", {
        name: "Owner",
        email,
        password,
      });
      expect(signUp.status).toBe(200);

      const signIn = await postAuth(testAuth.handler, "/sign-in/email", {
        email,
        password,
      });
      expect(signIn.status).toBe(200);

      const user = database.prepare('SELECT email, emailVerified FROM "user" WHERE email = ?').get(email) as {
        email: string;
        emailVerified: number;
      };
      expect(user).toMatchObject({ email, emailVerified: 0 });

      const account = database
        .prepare('SELECT providerId, userId FROM "account" WHERE providerId = ?')
        .get("credential") as { providerId: string; userId: string };
      expect(account.providerId).toBe("credential");
      expect(account.userId).toBeTruthy();

      const session = database.prepare('SELECT count(*) AS count FROM "session"').get() as { count: number };
      expect(session.count).toBeGreaterThanOrEqual(1);
    } finally {
      database.close();
    }
  }, migrationTestTimeoutMs);

  it("accepts self-hosted public origins even when the configured base URL is loopback", async () => {
    process.env.BETTER_AUTH_URL = "http://127.0.0.1:3000";
    process.env.PUBLIC_WEB_URL = "http://127.0.0.1:3000";
    process.env.BETTER_AUTH_TRUSTED_ORIGINS = "";

    const databasePath = migrateTempDatabase();
    const database = new Database(databasePath);
    try {
      const testAuth = betterAuth(buildAuthOptions(database));

      const signUp = await postAuth(
        testAuth.handler,
        "/sign-up/email",
        {
          name: "Public Owner",
          email: "public-owner@example.com",
          password: "correct-horse-password",
        },
        "http://109.123.229.21:3000",
      );

      expect(signUp.status).toBe(200);
    } finally {
      database.close();
    }
  }, migrationTestTimeoutMs);
});

function migrateTempDatabase(): string {
  const databasePath = path.join(mkdtempSync(path.join(tmpdir(), "platform-auth-")), "app.db");

  execFileSync(
    "go",
    ["run", "./cmd/migrate", "-database", databasePath, "-dir", "migrations/core", "up"],
    {
      cwd: repoRoot,
      env: {
        ...process.env,
        BETTER_AUTH_URL: "http://localhost:3000",
        GOCACHE: path.join(repoRoot, ".cache", "go-build"),
      },
      stdio: "pipe",
      timeout: 45_000,
    },
  );

  return databasePath;
}

async function postAuth(
  handler: (request: Request) => Promise<Response>,
  pathName: string,
  body: Record<string, unknown>,
  origin = "http://localhost:3000",
): Promise<Response> {
  return handler(
    new Request(`${origin}/api/auth${pathName}`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        origin,
      },
      body: JSON.stringify(body),
    }),
  );
}
